apiversion: apps/v1
kind: Deployment
metadata:
    name: my-application
spec:
    replicas: 2
    selector:
     matchLabels:
      app: nginx
    templates:
     metadata:
      labels:
       app: my-application
     spec:
       containers:
       - name: my-application
         image: narendrasinghcheema/tinku:10
      