version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - data_management

  data_management:
    build: ./  # Assuming your Dockerfile is in the current directory
    container_name: data_management
    depends_on:
      - mysqldb
    ports:
      - 9090:9090
    networks:
      - data_management

networks:
  data_management:
    driver: bridge
