version: "3.8"

networks:
  best:
    driver: bridge

    volumes:
     data_management_volume:

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - best
    volumes:
      - data_management_volume:/var/lib/mysql

  data_management:
    build: ./  # Assuming your Dockerfile is in the current directory
    container_name: data_management
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 9090:9090
    networks:
      - best
    volumes:
      - ./app1:/app1 
