version: "3.8"

networks:
  best:
    driver: bridge

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: Narendra#123
      MYSQL_DATABASE: user_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-pNarendra#123"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - best

  data_management:
    build: ./  # Assuming your Dockerfile is in the current directory
    container_name: data_management
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 9090:9090
    networks:
      - best 
