apiVersion: v1
kind: Service
metadata:
  name: my-service-application
spec:
  selector:
    app: my-application
  type: LoadBalancer
  ports:
    - protocol: tcp
      port: 80
      targetPort: 9090
